/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RevelationType = IDL.Variant({
  'Meccan' : IDL.Null,
  'Medinan' : IDL.Null,
});
export const Surah = IDL.Record({
  'verseCount' : IDL.Nat,
  'revelationType' : RevelationType,
  'arabicName' : IDL.Text,
  'number' : IDL.Nat,
  'englishTransliteration' : IDL.Text,
  'englishTranslation' : IDL.Text,
});
export const Verse = IDL.Record({
  'surahNumber' : IDL.Nat,
  'verseNumber' : IDL.Nat,
  'arabicText' : IDL.Text,
  'englishTranslation' : IDL.Text,
});

export const idlService = IDL.Service({
  'getSurahs' : IDL.Func([], [IDL.Vec(Surah)], ['query']),
  'getVersesBySurah' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RevelationType = IDL.Variant({
    'Meccan' : IDL.Null,
    'Medinan' : IDL.Null,
  });
  const Surah = IDL.Record({
    'verseCount' : IDL.Nat,
    'revelationType' : RevelationType,
    'arabicName' : IDL.Text,
    'number' : IDL.Nat,
    'englishTransliteration' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  const Verse = IDL.Record({
    'surahNumber' : IDL.Nat,
    'verseNumber' : IDL.Nat,
    'arabicText' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  
  return IDL.Service({
    'getSurahs' : IDL.Func([], [IDL.Vec(Surah)], ['query']),
    'getVersesBySurah' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };